import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="w-full border-b border-white/10 bg-[#0f1220]">
          <nav className="mx-auto max-w-6xl px-4 py-2 flex items-center justify-between">
            <div className="flex items-center gap-2">               
              <span className="text-lg font-bold opacity-80 text-yellow-200">Innovation Ideas</span>
            </div>
            <div className="flex items-center gap-2">
              {/* <a href="#" className="inline-flex items-center justify-center w-9 h-9 rounded-full bg-white/10 hover:bg-white/15 transition" aria-label="analytics">
                <span>♡</span>
              </a> */}
              {/* <a href="/create-question" className="inline-flex items-center justify-center w-9 h-9 rounded-full bg-white/10 hover:bg-white/15 transition" aria-label="team">
                <span>👥</span>
              </a>
              <a href="/" className="ml-2 inline-flex items-center rounded-full bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white hover:opacity-90 transition">
                เข้าสู่ระบบ
              </a> */}
            </div>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
