version: "3.9"

services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      # *** CHANGES HERE ***
      # Point to 'host.docker.internal' (Docker's way to reference the host) or 'localhost' if using host networking
      # The port remains 5432 if that's what the external/host postgres is using
      #POSTGRES_HOST: host.docker.internal  # Recommended for Docker Desktop/Linux with appropriate settings
      # OR (less reliable/secure, depends on Docker network mode):
      # POSTGRES_HOST: 172.17.0.1  # Docker default bridge gateway (less portable)
      # OR (if using 'host' network mode, which is not used here):
      POSTGRES_HOST: localhost
      
      POSTGRES_DB: eventfeedback
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      # *******************
      
      openai_api_key: ${OPENAI_API_KEY:-}
    # REMOVE 'depends_on' on 'event-db'
    # REMOVE 'healthcheck' if it was specifically tied to the db status
    ports: ["8000:8000"]
    networks: [eventnet] # Can keep this, or if you use 'host' networking, remove it. Keeping for consistency.
    restart: unless-stopped


  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://139.180.144.194:8000
      NEXT_PUBLIC_HOST_URL: http://139.180.144.194:3000
    depends_on: [backend]
    ports: ["3000:3000"]
    networks: [eventnet]
    restart: unless-stopped


# REMOVE the entire 'event-db' service block:
# event-db:
#   image: postgres:16-alpine
#   ... (etc.)

# REMOVE the 'depends_on' condition from the backend service:
#   depends_on:
#     event-db:
#       condition: service_healthy

# REMOVE the 'volumes' block if 'db_data' is no longer needed
# volumes:
#   db_data:

networks:
  eventnet: {}

# REMOVE the 'volumes' block since 'event-db' is gone
# volumes:
#   db_data: {}