IF OBJECT_ID('dbo.vProjectSubmissionExport', 'V') IS NOT NULL
    DROP VIEW dbo.vProjectSubmissionExport;
GO

CREATE VIEW dbo.vProjectSubmissionExport
AS
SELECT
    p.ProjectId,
    p.EventYear,
    p.SubmissionTypeCode,
    p.SubmissionTypeNameTh,
    p.TeamName,

    p.ChallengeNo,
    p.ChallengeText,

    p.IdeaSourceCoPs,
    p.IdeaSourceCoPsDetail,
    p.IdeaSourceLR,
    p.IdeaSourceLRDetail,
    p.IdeaSourceResearch,
    p.IdeaSourceResearchDetail,
    p.IdeaSourceExperience,
    p.IdeaSourceExperienceDetail,
    p.IdeaSourceStudyVisit,
    p.IdeaSourceStudyVisitDetail,
    p.IdeaSourceKnowledgeExchange,
    p.IdeaSourceKnowledgeExchangeDetail,
    p.IdeaSourceInnovationDatabase,
    p.IdeaSourceInnovationDatabaseDetail,
    p.IdeaSourceMarketStudy,
    p.IdeaSourceMarketStudyDetail,
    p.IdeaSourceVOS,
    p.IdeaSourceVOSDetail,
    p.IdeaSourceOther,
    p.IdeaSourceOtherDetail,

    p.TargetCustomerHtml,

    p.InnovationTypeNo,
    p.InnovationTypeText,

    p.IdeaConceptHtml,
    p.ExpectedBenefitHtml,

    p.GenCapProjectManagement,
    p.GenCapCommunications,
    p.GenCapMarketing,
    p.GenCapFinancialBusinessAnalysis,
    p.GenCapCustomerManagement,
    p.GenCapStakeholderPartnership,
    p.GenCapOther,
    p.GenCapOtherDetail,

    p.DigitalCapProductDevelopment,
    p.DigitalCapCodingProgramming,
    p.DigitalCapDataAnalysis,
    p.DigitalCapUiUxGraphicDesign,
    p.DigitalCapSoftwareTooling,
    p.DigitalCapOther,
    p.DigitalCapOtherDetail,

    p.HackathonMotivationHtml,

    MAX(CASE WHEN m.MemberSeq = 1 THEN m.EmpCode END) AS Member1EmpCode,
    MAX(CASE WHEN m.MemberSeq = 1 THEN m.FullNameTh END) AS Member1FullNameTh,
    MAX(CASE WHEN m.MemberSeq = 1 THEN m.PositionName END) AS Member1PositionName,
    MAX(CASE WHEN m.MemberSeq = 1 THEN m.OrgName END) AS Member1OrgName,
    MAX(CASE WHEN m.MemberSeq = 1 THEN m.MobileNo END) AS Member1MobileNo,

    MAX(CASE WHEN m.MemberSeq = 2 THEN m.EmpCode END) AS Member2EmpCode,
    MAX(CASE WHEN m.MemberSeq = 2 THEN m.FullNameTh END) AS Member2FullNameTh,
    MAX(CASE WHEN m.MemberSeq = 2 THEN m.PositionName END) AS Member2PositionName,
    MAX(CASE WHEN m.MemberSeq = 2 THEN m.OrgName END) AS Member2OrgName,
    MAX(CASE WHEN m.MemberSeq = 2 THEN m.MobileNo END) AS Member2MobileNo,

    MAX(CASE WHEN m.MemberSeq = 3 THEN m.EmpCode END) AS Member3EmpCode,
    MAX(CASE WHEN m.MemberSeq = 3 THEN m.FullNameTh END) AS Member3FullNameTh,
    MAX(CASE WHEN m.MemberSeq = 3 THEN m.PositionName END) AS Member3PositionName,
    MAX(CASE WHEN m.MemberSeq = 3 THEN m.OrgName END) AS Member3OrgName,
    MAX(CASE WHEN m.MemberSeq = 3 THEN m.MobileNo END) AS Member3MobileNo,

    MAX(CASE WHEN m.MemberSeq = 4 THEN m.EmpCode END) AS Member4EmpCode,
    MAX(CASE WHEN m.MemberSeq = 4 THEN m.FullNameTh END) AS Member4FullNameTh,
    MAX(CASE WHEN m.MemberSeq = 4 THEN m.PositionName END) AS Member4PositionName,
    MAX(CASE WHEN m.MemberSeq = 4 THEN m.OrgName END) AS Member4OrgName,
    MAX(CASE WHEN m.MemberSeq = 4 THEN m.MobileNo END) AS Member4MobileNo,

    MAX(CASE WHEN m.MemberSeq = 5 THEN m.EmpCode END) AS Member5EmpCode,
    MAX(CASE WHEN m.MemberSeq = 5 THEN m.FullNameTh END) AS Member5FullNameTh,
    MAX(CASE WHEN m.MemberSeq = 5 THEN m.PositionName END) AS Member5PositionName,
    MAX(CASE WHEN m.MemberSeq = 5 THEN m.OrgName END) AS Member5OrgName,
    MAX(CASE WHEN m.MemberSeq = 5 THEN m.MobileNo END) AS Member5MobileNo,

    p.StatusCode,
    p.SubmittedAt,
    p.CreatedByEmpCode,
    p.CreatedAt,
    p.UpdatedByEmpCode,
    p.UpdatedAt
FROM dbo.ProjectSubmission p
LEFT JOIN dbo.ProjectSubmissionMember m
    ON p.ProjectId = m.ProjectId
GROUP BY
    p.ProjectId,
    p.EventYear,
    p.SubmissionTypeCode,
    p.SubmissionTypeNameTh,
    p.TeamName,
    p.ChallengeNo,
    p.ChallengeText,
    p.IdeaSourceCoPs,
    p.IdeaSourceCoPsDetail,
    p.IdeaSourceLR,
    p.IdeaSourceLRDetail,
    p.IdeaSourceResearch,
    p.IdeaSourceResearchDetail,
    p.IdeaSourceExperience,
    p.IdeaSourceExperienceDetail,
    p.IdeaSourceStudyVisit,
    p.IdeaSourceStudyVisitDetail,
    p.IdeaSourceKnowledgeExchange,
    p.IdeaSourceKnowledgeExchangeDetail,
    p.IdeaSourceInnovationDatabase,
    p.IdeaSourceInnovationDatabaseDetail,
    p.IdeaSourceMarketStudy,
    p.IdeaSourceMarketStudyDetail,
    p.IdeaSourceVOS,
    p.IdeaSourceVOSDetail,
    p.IdeaSourceOther,
    p.IdeaSourceOtherDetail,
    p.TargetCustomerHtml,
    p.InnovationTypeNo,
    p.InnovationTypeText,
    p.IdeaConceptHtml,
    p.ExpectedBenefitHtml,
    p.GenCapProjectManagement,
    p.GenCapCommunications,
    p.GenCapMarketing,
    p.GenCapFinancialBusinessAnalysis,
    p.GenCapCustomerManagement,
    p.GenCapStakeholderPartnership,
    p.GenCapOther,
    p.GenCapOtherDetail,
    p.DigitalCapProductDevelopment,
    p.DigitalCapCodingProgramming,
    p.DigitalCapDataAnalysis,
    p.DigitalCapUiUxGraphicDesign,
    p.DigitalCapSoftwareTooling,
    p.DigitalCapOther,
    p.DigitalCapOtherDetail,
    p.HackathonMotivationHtml,
    p.StatusCode,
    p.SubmittedAt,
    p.CreatedByEmpCode,
    p.CreatedAt,
    p.UpdatedByEmpCode,
    p.UpdatedAt;
GO